#!/usr/bin/php -c/etc/phpd.ini
<?php

/**
 * @license PHP Daemon
 * http://www.xarg.org/2016/07/how-to-write-a-php-daemon/
 *
 * Copyright (c) 2016, Robert Eisele (robert@xarg.org)
 * Dual licensed under the MIT or GPL Version 2 licenses.
 **/

require 'config.php';

chdir(DAEMON_ROOT);

if (PHP_SAPI !== 'cli') {
	exit;
}

if (DAEMON_FORK && 0 !== pcntl_fork()) {
	exit;
}

Main::log(E_NOTICE, DAEMON_NAME . ' started at ' . date(DATE_RFC822));

// Used for signals
declare(ticks = 1);

Main::registerSignal();

set_error_handler("Main::handleError");

if (DAEMON_FORK) {

	Main::registerEnv();

	/* Reduce verbosity, we don't have STDOUT/STDERR open anymore*/
	ini_set("display_errors", 0);
}

Main::loop();

/* Delete PID file after shutdown */
unlink(DAEMON_PID);

Main::log(E_NOTICE, DAEMON_NAME . ' shut down normally at ' . date(DATE_RFC822));

